### ISSUE TITLE
Multi thread example

### ISSUE THREAD

**Issue by tankche1** [b-inary/postflop-solver#11]
Hi,

Thanks for the great work!

 It seems that the example run much slower than in the desktop app.

I notice that multi-thread is implemented in the desktop application but not in this code.

Can you give an example of how to do that?

**Comment by b-inary** [comment]
This library utilizes the [rayon](https://github.com/rayon-rs/rayon) crate for multithreading. The `into_par_iter()` method in the following snippet does the parallelization.

https://github.com/b-inary/postflop-solver/blob/f9b2dedc5b0d23d8971bd76cf73487212c62d3d6/src/utility.rs#L15-L23

So, the example should run almost as fast as the desktop app if the **compiler options are the same**:

- Please first make sure that you are running a release build (compile with the `--release` flag).
- Enabling SIMD instructions is also important (for example, set the environment variable `RUSTFLAGS="-C target-feature=+avx"`).
- Add `codegen-units = 1` and `lto = true` to `[profile.release]` in the `Cargo.toml` (the [document](https://doc.rust-lang.org/cargo/reference/profiles.html)).

The desktop app also enables the `custom-alloc` feature of this library. This crate feature might improve the performance, but it crashes if you solve multiple instances simultaneously in a program.

I hope the above information will help.

**Comment by tankche1** [comment]
Thank you for the quick response.

Following your advise, 
I do:
1. ```cargo run --release```


2. Add the following in .cargo/config.toml
 ```
[build]
rustflags = ["-C", "target-feature=+avx"]
```
3. Add the lines in cargo.toml

However, for the example case in 40iter, the solver took 14.12s while desktop took 8.19s (8 threads) and 7.16s (16 threads).

I wonder to i need to set threads num in the example code or i miss something.

**Comment by b-inary** [comment]
By default, the number of threads should be automatically detected. If you want to control the number of threads manually, please see [rayon's FAQ](https://github.com/rayon-rs/rayon/blob/master/FAQ.md).

I am sorry, but if the above settings do not resolve the problem, then I have no idea why. The desktop app is doing nothing special other than the above configuration.

**Comment by tankche1** [comment]
Yeah. It seems that the only difference is custom-alloc and different libraries for multi-thread.

**Comment by b-inary** [comment]
Closes due to inactivity.

> It seems that the only difference is custom-alloc and **different libraries for multi-thread**.

The desktop app also uses the same rayon library, so I think there is some misunderstanding.
