### ISSUE TITLE
Raked calculations

### ISSUE THREAD

**Issue by 1R0NYMAN** [b-inary/postflop-solver#12]
Is it possible to prerform raked calculations (e.g. rake 5% with 1 BB cap)?

**Comment by b-inary** [comment]
It is probably possible, but we are currently planning to implement node-locking and reduced saving features (e.g., excluding river actions) ahead of time. Then, if we also implement raked calculation, it could threaten commercial solvers. I am not sure if that would be a good thing or not.

Another problem is that the game is no longer zero-sum when raked, so the CFR algorithm is no longer guaranteed to converge to the Nash equilibrium. Also, the optimality of the Nash equilibrium becomes questionable.

**Comment by 1R0NYMAN** [comment]
Node-locking and reduced saving features will threaten commertical solvers way more because those are the most valuable practical use-cases of the solvers. I reached very low around 0% in non-zero sum modes (raked and ICM) in GTO+ and Piosolver and the results are almost identical.
