### ISSUE TITLE
Is there a limit to the number of cores used?

### ISSUE THREAD

**Issue by mhluska** [b-inary/postflop-solver#33]
I noticed that there doesn't seem to be a difference from running this on a machine with 128 cores to 192 cores.

**Comment by b-inary** [comment]
There is no explicit limit on the number of threads, but I don't think it makes sense to go from 128 threads to 192 threads. This is because the memory I/O becomes the bottleneck in such a case, not the CPU. Using too many threads just increases the idle time of the CPU.

**Comment by mhluska** [comment]
Do you have any recommendations on working around the memory bottleneck?

**Comment by BenTheKush** [comment]
It's basically just a quirk of the problem.

One way around this: if you have 192 cores and have the memory, just run 3 solves at once. This will minimize CPU idle time and make better use of all cores

**Comment by mhluska** [comment]
Wouldn't that require splitting the problem into three pieces, solving them concurrently in those 3 solves and then somehow merging them back together? Or do you mean just solve 3 different games concurrently?

**Comment by bkushigian** [comment]
> Wouldn't that require splitting the problem into three pieces, solving them concurrently and then somehow merging the results back together? Or do you mean just solve 3 different games concurrently?

Yeah, I meant if you're running a bunch of sims just run 3 in parallel to better utilize CPUs. You probably need to set an environment variable to set the max number of CPUs being used at a time (to prevent context switching which is expensive)

If you're running a single sim you'll probably just have to wait a bit longer

**Comment by b-inary** [comment]
Running multiple different instances at the same time may or may not improve performance, I think it depends on the environment. Anyway, a reasonable amount of memory access is inevitable by the nature of the CFR algorithm, so there is not much I can do about it. I would like to close this issue.
