### ISSUE TITLE
Unclear how to save a file

### ISSUE THREAD

**Issue by 1R0NYMAN** [b-inary/postflop-solver#37]
It's unclear in basic.rs how to save a file, I tried this
  let config = config::standard();
  let mut file = BufWriter::new(File::create("test.bin").unwrap());
  bincode::encode_into_std_write(&game, &mut file, config).unwrap();
It doesn't work, can you add some instructions in basic.rs, how to save a file

**Comment by b-inary** [comment]
Basically, please use `save_data_to_file()` and `load_data_from_file()` to save/load files. 
I will add more detailed documentation and examples soon.
