### ISSUE TITLE
I wish I had a clue how to use this..

### ISSUE THREAD

**Issue by beautifulbran** [b-inary/postflop-solver#38]
I'm pretty new when it comes to this stuff. Installing python stuff is easy but no idea how to even begin here. I've downloaded the Desktop Postflop application. Could you maybe explain to me in beginners terms how I would go about running this and using it along with Desktop Postflop or is it even supposed to be used in combination with that application? Sorry and thank you haha!

**Comment by b-inary** [comment]
As @dpmaloney said, if you are just using the Desktop Postflop application, you don't need to worry about this repository. However, if you are interested in the logic behind it, this should be an interesting repository to explore.
