### ISSUE TITLE
node lock

### ISSUE THREAD

**Issue by tankche1** [b-inary/postflop-solver#39]
Any plan to support node lock?  It looks straightforward from the current code. Specifically, can we call the solve function after we run some game.play(), and then it will start searching from the current state?  This may need some modification in solve_step to determine the current player and starting node.

**Comment by mhluska** [comment]
If it's straightforward, why don't you submit a PR?

**Comment by b-inary** [comment]
I wouldn't say the implementation is complete, but this engine repository actually already supports node locking. It supports normal node locking ([test code](https://github.com/b-inary/postflop-solver/blob/ff7a40abb411f3b27589dc6dfd4aa7557c43fcf4/src/game/tests.rs#L850)), as well as partial range node locking ([test code](https://github.com/b-inary/postflop-solver/blob/ff7a40abb411f3b27589dc6dfd4aa7557c43fcf4/src/game/tests.rs#L911)).

I also note that you seem to misunderstand the principle of node locking. Node locking can affect nodes before the locked node. For example, if we know that the opponent will always fold after our bet (i.e., the opponent's future node is locked), then we would increase our bluff bets. This is completely different from just solving with different ranges.
