### ISSUE TITLE
lack of symmetry in game.rs

### ISSUE THREAD

**Issue by bgnori** [b-inary/postflop-solver#8]
I see these in L1201 and L1202

https://github.com/b-inary/postflop-solver/blob/3f665d59ac958b155350a8fab15eadee685d86aa/src/game.rs#L1201-L1202

But in L1226 and L1227

https://github.com/b-inary/postflop-solver/blob/3f665d59ac958b155350a8fab15eadee685d86aa/src/game.rs#L1226-L1227

I do not know much about this software, but it seems something wrong.

**Comment by b-inary** [comment]
Oops, it works practically fine, but L1226 is incorrect. Thanks for the report!
