### ISSUE TITLE
train players reach variable may not be used.

### ISSUE THREAD

**Issue by unacowa** [b-inary/postflop-solver#9]
In solver, variable `reach_actions` are multiplied based on the strategy, then passed to the child nodes.
But, I think the `reach` argument is never used for computetion.

I tried to just pass the result to the child node without multiply, but result did not seem to change.

```diff
         // update the reach probabilities
-        #[cfg(feature = "custom-alloc")]
-        let mut reach_actions = {
-            let mut tmp = Vec::with_capacity_in(strategy.len(), StackAlloc);
-            tmp.extend_from_slice(&strategy);
-            tmp
-        };
-        #[cfg(not(feature = "custom-alloc"))]
-        let mut reach_actions = strategy.clone();
-        reach_actions.chunks_exact_mut(num_hands).for_each(|row| {
-            mul_slice(row, reach);
-        });
+        // #[cfg(feature = "custom-alloc")]
+        // let mut reach_actions = {
+        //     let mut tmp = Vec::with_capacity_in(strategy.len(), StackAlloc);
+        //     tmp.extend_from_slice(&strategy);
+        //     tmp
+        // };
+        // #[cfg(not(feature = "custom-alloc"))]
+        // let mut reach_actions = strategy.clone();
+        // reach_actions.chunks_exact_mut(num_hands).for_each(|row| {
+        //     mul_slice(row, reach);
+        // });
```

```diff
-                row(&reach_actions, action, num_hands),
+                // row(&reach_actions, action, num_hands),
+               reach,
```

Is this unnecessary code?

https://github.com/b-inary/postflop-solver/blob/main/src/solver.rs#L262

**Comment by b-inary** [comment]
Thanks for the report! You are right, now the `reach` argument is not used. I will remove the `reach` argument soon.

Historical reason: Before 164a9dd, the variable `reach_actions` was added to `cum_strategy`, following the original definition of the CFR algorithm. However, to obtain meaningful EVs for all actions, we need to update the strategy even if the reaching probability is (almost) zero. This update removes the use of the `reach` argument.
